### ISSUE TITLE
抱歉，无关的问题

### ISSUE THREAD

**Issue by dairectx** [R32/asram#1]
因为没有办法获取你的联系方式，所以只好在这里开一个无关的issue，抱歉。

很意外在Github上能搜索到对haxe感兴趣的国人，我们的游戏公司正在寻找会haxe的开发者，不知道你是否有兴趣加入？
我的个人联系方式是: dxw2qzy at gmail dot com （去掉中间的2）
希望你能来信。

**Comment by R32** [comment]
我现在上班, 而且 haxe 开发游戏目前只有 flash 算是成熟,其它平台我感觉不太好!

**Comment by dairectx** [comment]
你指的其他平台可能是指OpenFl和Heap等这类游戏框架对flash平台之外的支持程度吧？的确还不够成熟。
但haxe的跨平台的魅力不仅仅体现在渲染上，更体现在前后端的逻辑通用上。
比如:
http://proletariat.com/blog/2015/04/16/world-zombination-tools-roundup/
http://nadako.tumblr.com/post/113390739725/a-success-story-for-haxe

Anyway, 如果你热爱游戏开发，并且考虑换工作的话，请务必给我来信。 :)

**Comment by R32** [comment]
好的
